// Copyright 2012 Google Inc. All rights reserved.
// Container Version: 2
(function(w,g){w[g]=w[g]||{};})(window,'google_tag_manager');(function(){














var Fb=this;/*
 jQuery v1.9.1 (c) 2005, 2012 jQuery Foundation, Inc. jquery.org/license. */
var Gb=/\[object (Boolean|Number|String|Function|Array|Date|RegExp)\]/,Hb=function(a){if(null==a)return String(a);var b=Gb.exec(Object.prototype.toString.call(Object(a)));return b?b[1].toLowerCase():"object"},Ib=function(a,b){return Object.prototype.hasOwnProperty.call(Object(a),b)},Ha=function(a){if(!a||"object"!=Hb(a)||a.nodeType||a==a.window)return!1;try{if(a.constructor&&!Ib(a,"constructor")&&!Ib(a.constructor.prototype,"isPrototypeOf"))return!1}catch(c){return!1}for(var b in a);return void 0===
b||Ib(a,b)},Ea=function(a,b){var c=b||("array"==Hb(a)?[]:{}),d;for(d in a)if(Ib(a,d)){var e=a[d];"array"==Hb(e)?("array"!=Hb(c[d])&&(c[d]=[]),c[d]=Ea(e,c[d])):Ha(e)?(Ha(c[d])||(c[d]={}),c[d]=Ea(e,c[d])):c[d]=e}return c};var Ca={},lb=null,Jb=Math.random();Ca.f="GTM-TBK9BP";var Kb=null,wa=null,Ua=!1,Lb="//www.googletagmanager.com/a?id="+Ca.f+"&cv=2",Mb={},Nb={},Va={};var Ya,Za,Ob,Pb,Qb,Rb,Sb,Tb,Ub,Vb,Wb,Xb,Yb,Zb,$b,ac,bc,cc,dc,ec,fc,gc,hc,ic,jc,kc,lc,mc,nc,oc,pc,qc,rc,sc,tc,uc,vc,wc,xc,yc,zc,Ac,Bc,Cc,Dc,Ec,Fc,Gc,Hc,Ic,Jc,Kc,Lc,Mc,Nc,Oc,Pc,Qc,Rc,Sc,Tc,Uc,Vc,Wc,Xc,Yc,Zc,$c,ad,bd,cd,dd,ed,fd,gd,hd,id,jd,kd,ld,md,nd,od,pd,qd,rd,sd,td,ud,vd,wd,xd,yd,zd,Ad,Bd,Cd,Dd,Ed,Fd,Gd,Hd,Id,Jd,Kd,Ld,Md,Nd,Od,Pd,Qd,Rd,Sd,Td,Ud,Vd,Wd,Xd,Yd,Zd,$d,ae,be,ce,de,ee,fe,ge,he,ie,je,ke,le,me,ne,oe,pe,qe,re,se,te,ue,ve,we,xe,ye,ze,Ae,Be,Ce,De,Ee,Fe,Ge,He,Ie,Je,Ke,Le,Me,Ne,Oe,Pe,Qe,Re,Se,
Te,Ue,Ve,We,Xe,Ye,Ze,$e,af,bf,cf,df,ef,ff,gf,hf,jf,kf,lf,mf,nf,of,pf,qf,rf,sf,tf,uf,vf,wf,xf,yf,zf,Af,Bf,Cf,Df,Ef,Ff,Gf,Hf,If,Jf,Kf;
(function(){var a=function(a){return{toString:function(){return a}}};Ob=a("");Pb=a("0");Qb="";Rb=a("");Sb=a("");Tb=a("");Ub=a("");Vb=a("");Wb=a("");Xb=a("");Yb=a("");Zb=a("2");$b=a("3");ac=a("");bc=a("");cc=a("");
dc=a("");ec=a("");fc=a("");gc=a("");hc=a("");ic=a("");jc=a("");kc=a("");lc=a("");mc=a("");nc=a("");oc=a("");pc=a("");qc=a("");
rc=a("");sc=a("");tc=a("");uc=a("");vc=a("");wc=a("");xc=a("4");yc=a("");zc=a("");Ac=a("");Bc=a("");Cc=a("");Dc=a("");Ec=a("");Fc=a("");Gc=a("");Hc=a("");
Ic=a("");Jc=a("");Kc=a("");Lc=a("");Mc=a("");Nc=a("");Oc=a("");Pc=a("");Qc=a("");Rc=a("5");Sc=a("");Tc=a("");Uc=a("6");Vc=a("");Wc=a("");Xc=a("");Yc=a("");
Zc=a("");$c=a("");ad=a("");bd=a("");cd=a("7");dd=a("");ed=a("8");fd=a("");gd=a("");hd=a("");id=a("");jd=a("");kd=a("");ld=a("9");md=a("");nd=a("");
od=a("");pd=a("");qd=a("");rd=a("");sd=a("");td=a("");ud=a("");vd=a("");wd=a("");xd=a("");yd=a("");Ya=a("10");zd=a("");Ad=a("16");Bd=a("17");Cd=a("");Dd=a("");
Ed=a("");Fd=a("");Gd=a("");Hd=a("");Id=a("");Jd=a("");Za=a("11");Kd=a("");Ld=a("");Md=a("");Nd=a("");Od=a("");Pd=a("");Qd=a("");Rd=a("");Sd=a("");Td=a("");Ud=a("12");Vd=a("");Wd=a("");
Xd=a("");Yd=a("");Zd=a("");$d=a("");ae=a("");be=a("");ce=a("");de=a("");ee=a("");fe=a("");ge=a("");he=a("");ie=a("");je=a("");ke=a("");le=a("");me=a("");ne=a("");oe=a("");pe=a("");
qe=a("");re=a("");se=a("");te=a("");ue=a("");ve=a("");we=a("");xe=a("");ye=a("");ze=a("");Ae=a("");Be=a("");Ce=a("");De=a("");Ee=a("");Fe=a("");Ge=a("");He=a("");Ie=a("");
Je=a("");Ke=a("");Le=a("");Me=a("");Ne=a("");Oe=a("");Pe=a("");Qe=a("");Re=a("");Se=a("");Te=a("");Ue=a("");Ve=a("");We=a("");Xe=a("14");Ye=
a("");Ze=a("");$e=a("");af=a("");bf=a("");cf=a("");df=a("");ef=a("");ff=a("");gf=a("");hf=a("");jf=a("");kf=a("");lf=a("");mf=a("");nf=a("");of=a("");
pf=a("");qf=a("");rf=a("");sf=a("");tf=a("");uf="";vf=a("");wf=a("");xf=a("");yf=a("");zf=a("");Af=a("15");Bf=a("");Cf=a("");Df=a("");Ef=a("");Ff=a("");Gf=
a("");Hf=a("");If=a("");Jf=a("");Kf=a("")})();var Eb=function(a,b){Ea(a,b)},vb=function(){},S=function(a){return"function"==typeof a},$a=function(a){return"[object Array]"==Object.prototype.toString.call(Object(a))},Lf=function(a){return"number"==Hb(a)&&!isNaN(a)},Mf=function(a){return/^[0-9]+$/.test(a)},ib=function(a){return"string"==Hb(a)},Nf=function(a,b){if(Array.prototype.indexOf){var c=a.indexOf(b);return"number"==typeof c?c:-1}for(var d=0;d<a.length;d++)if(a[d]===b)return d;return-1},Of=function(a,b){if(a&&$a(a)&&0!=a.length)for(var c=
0;c<a.length;c++)if(a[c]&&b(a[c]))return a[c]},va=function(a){return a?a.replace(/^\s+|\s+$/g,""):""},X=function(a){return Math.round(Number(a))||0},Ja=function(a){return"false"==String(a).toLowerCase()?!1:!!a},Pf=function(a){var b=[];if($a(a))for(var c=0;c<a.length;c++)b.push(String(a[c]));return b},L=function(){return new Date},Ba=function(a,b){if(!Lf(a)||!Lf(b)||a>b)a=0,b=2147483647;return Math.floor(Math.random()*(b-a+1)+a)},Qf=function(){this.prefix="gtm.";this.values={}};
Qf.prototype.set=function(a,b){this.values[this.prefix+a]=b};Qf.prototype.get=function(a){return this.values[this.prefix+a]};Qf.prototype.contains=function(a){return void 0!==this.get(a)};
var Rf=function(a,b,c){try{if(!a[Zd])return a[Ya](a,b||vb,c||vb);c&&c()}catch(d){}return!1},Sf=function(a,b){function c(b,c){a.contains(b)||a.set(b,[]);a.get(b).push(c)}for(var d=va(b).split("&"),e=0;e<d.length;e++)if(d[e]){var f=d[e].indexOf("=");0>f?c(d[e],"1"):c(d[e].substring(0,f),d[e].substring(f+1))}},Tf=function(a){var b=a?a.length:0;return 0<b?a[b-1]:""},Uf=function(a){var b=Ca.f;return function(){return a(b)}},Vf=function(a){for(var b=0;b<a.length;b++)a[b]()},Ga=function(){return"gtm"+Wf()},
Wf=function(){var a=lb.sequence||0;lb.sequence=a+1;return a},Ia=function(a,b,c){return a&&a.hasOwnProperty(b)?a[b]:c},Xf=function(a){return null!==a&&void 0!==a&&void 0!==a.length},Yf=function(a,b){0==b?a.fc=!0:a.la=!0;var c=a.i;a.G&&(a.G.xb[c]=b);Mb[c]&&(Mb[c].state=b)},Zf=function(a,b){return"function"!=typeof String.prototype.startsWith?0===a.indexOf(b):a.startsWith(b)},$f=function(a,b){a.sort(function(a,d){return b(a,d)?-1:b(d,a)?1:0})};var z=window,P=document,bg=navigator,Ta=function(a,b){var c=z[a];z[a]=void 0===c?b:c;return z[a]},ka=function(a,b,c,d){return(d||"http:"!=z.location.protocol?a:b)+c},cg=function(a){var b=P.getElementsByTagName("script")[0]||P.body||P.head;b.parentNode.insertBefore(a,b)},pb=function(a,b){b&&(a.addEventListener?a.onload=b:a.onreadystatechange=function(){a.readyState in{loaded:1,complete:1}&&(a.onreadystatechange=null,b())})},u=function(a,b,c){var d=P.createElement("script");d.type="text/javascript";
d.async=!0;d.src=a;pb(d,b);c&&(d.onerror=c);cg(d);return d},Wa=function(a,b){var c=P.createElement("iframe");c.height="0";c.width="0";c.style.display="none";c.style.visibility="hidden";cg(c);pb(c,b);void 0!==a&&(c.src=a);return c},F=function(a,b,c){var d=new Image(1,1);d.onload=function(){d.onload=null;b&&b()};d.onerror=function(){d.onerror=null;c&&c()};d.src=a},pa=function(a,b,c,d){a.addEventListener?a.addEventListener(b,c,!!d):a.attachEvent&&a.attachEvent("on"+b,c)},na=function(a,b,c,d){a.removeEventListener?
a.removeEventListener(b,c,!!d):a.detachEvent&&a.detachEvent("on"+b,c)},w=function(a){z.setTimeout(a,0)},rb=!1,sb=[],dg=function(a){if(!rb){var b=P.createEventObject,c="complete"==P.readyState,d="interactive"==P.readyState;if(!a||"readystatechange"!=a.type||c||!b&&d){rb=!0;for(var e=0;e<sb.length;e++)w(sb[e])}sb.push=function(){for(var a=0;a<arguments.length;a++)w(arguments[a]);return 0}}},eg=0,fg=function(){if(!rb&&140>eg){eg++;try{P.documentElement.doScroll("left"),dg()}catch(a){z.setTimeout(fg,
50)}}},ha=function(a){var b=P.getElementById(a);if(b&&ta(b,"id")!=a)for(var c=1;c<document.all[a].length;c++)if(ta(document.all[a][c],"id")==a)return document.all[a][c];return b},ta=function(a,b){return a&&b&&a.attributes&&a.attributes[b]?a.attributes[b].value:null},gg=function(a){return a.target||a.srcElement||{}},ua=function(a){var b=a.innerText||a.textContent||"";b&&" "!=b&&(b=b.replace(/^[\s\xa0]+|[\s\xa0]+$/g,""));b&&(b=b.replace(/(\xa0+|\s{2,}|\n|\r\t)/g," "));return b},yb=function(a){var b=
P.createElement("div");b.innerHTML="A<div>"+a+"</div>";b=b.lastChild;for(var c=[];b.firstChild;)c.push(b.removeChild(b.firstChild));return c},hg=function(a,b,c){c=c||100;for(var d={},e=0;e<b.length;e++)d[b[e]]=!0;var f=a;for(e=0;f&&e<=c;e++){if(d[String(f.tagName).toLowerCase()])return f;f=f.parentElement}return null},ig=!1,ng=[],og=function(){if(!ig){ig=!0;for(var a=0;a<ng.length;a++)w(ng[a])}},pg=function(a){a=a||z;var b=a.location.href,c=b.indexOf("#");return 0>c?"":b.substring(c+1)},wb=function(a){window.console&&
window.console.log&&window.console.log(a)};var qg=function(a,b){for(var c=a.split("&"),d=0;d<c.length;d++){var e=c[d].split("=");if(decodeURIComponent(e[0]).replace(/\+/g," ")==b)return decodeURIComponent(e.slice(1).join("=")).replace(/\+/g," ")}},V=function(a,b,c,d,e){var f,g=(a.protocol.replace(":","")||z.location.protocol.replace(":","")).toLowerCase();b&&(b=String(b).toLowerCase());switch(b){case "protocol":f=g;break;case "host":f=(a.hostname||z.location.hostname).split(":")[0].toLowerCase();if(c){var h=/^www\d*\./.exec(f);h&&h[0]&&(f=
f.substr(h[0].length))}break;case "port":f=String(1*(a.hostname?a.port:z.location.port)||("http"==g?80:"https"==g?443:""));break;case "path":f="/"==a.pathname.substr(0,1)?a.pathname:"/"+a.pathname;var k=f.split("/");0<=Nf(d||[],k[k.length-1])&&(k[k.length-1]="");f=k.join("/");break;case "query":f=a.search.replace("?","");e&&(f=qg(f,e));break;case "fragment":f=a.hash.replace("#","");break;default:f=a&&a.href}return f},xa=function(a){var b="";if(a&&a.href){var c=a.href.indexOf("#");b=0>c?a.href:a.href.substr(0,
c)}return b},U=function(a){var b=P.createElement("a");a&&(b.href=a);return b};var qa=function(a,b){var c=function(){};c.prototype=a.prototype;var d=new c;a.apply(d,Array.prototype.slice.call(arguments,1));return d};var jb=function(a){return encodeURIComponent(a)},da=function(a){var b=["veinteractive.com","ve-interactive.cn"];if(!a)return!1;var c=V(U(a),"host");if(!c)return!1;for(var d=0;b&&d<b.length;d++){var e=b[d]&&b[d].toLowerCase();if(e){var f=c.length-e.length;0<f&&"."!=e.charAt(0)&&(f--,e="."+e);if(0<=f&&c.indexOf(e,f)==f)return!0}}return!1};
var Q=function(a,b,c){for(var d={},e=!1,f=0;a&&f<a.length;f++)a[f]&&a[f].hasOwnProperty(b)&&a[f].hasOwnProperty(c)&&(d[a[f][b]]=a[f][c],e=!0);return e?d:null},nb=function(a,b){for(var c=[],d=0;a&&d<a.length;d++)a[d]&&a[d].hasOwnProperty(b)&&c.push(a[d][b]);return c},Da=function(a,b){Ea(a,b)},Ka=function(a){return X(a)},zb=function(a,b){return Nf(a,b)};var rg={event:function(a){var b=a[1];if(ib(b)&&!(3<a.length)){var c;if(2<a.length){if(!Ha(a[2]))return;c=a[2]}var d=c,e={event:b};d&&(d=Ea(d,void 0),e.eventModel=d,e.eventCallback=d.eventCallback);return e}},set:function(a){var b;2==a.length&&Ha(a[1])?b=Ea(a[1],void 0):3==a.length&&ib(a[1])&&(b={},b[a[1]]=a[2]);if(b)return b._clear=!0,b},js:function(a){if(2==a.length&&a[1].getTime)return{event:"gtm.js","gtm.start":a[1].getTime()}}};var sg=new Qf,tg={},vg={set:function(a,b){Ea(ug(a,b),tg)},get:function(a){return Z(a,2)},reset:function(){sg=new Qf;tg={}}},Z=function(a,b){var c;if(2!=b)c=sg.get(a);else a:{for(var d=a.split("."),e=0,f=tg.eventModel;void 0!==f&&e<d.length;e++)f=f[d[e]];if(void 0!==f||1<e)c=f;else{var g=tg;for(e=0;e<d.length;e++){if(void 0===g[d[e]]){c=void 0;break a}g=g[d[e]]}c=g}}return c},wg=function(a,b){sg.set(a,b);Ea(ug(a,b),tg)},ug=function(a,b){for(var c={},d=c,e=a.split("."),f=0;f<e.length-1;f++)d=d[e[f]]=
{};d[e[e.length-1]]=b;return c};var xg=!1,yg=!1;var zg=Math.random(),Ag="0.050000">zg;
var Bg=function(a,b){if(Ag){var c=Lb,d=function(a,b){b&&(c+=a+encodeURIComponent(b))};d("&v=","t");d("&n=",a);d("&s=",b&&b.state);d("&h=",b&&b.hideLatency);d("&g=",b&&b.gaLatency);d("&p=",b&&b.loadBy);d("&o=",b&&b.timeout);d("&l=",L().getTime()-X(Kb));c+="&sr=0.050000";d("&ps=",zg);d("&cb=",Ba());F(c)}},Cg=vb,Dg=function(){var a=!1;
};var Fg=function(a){var b=lb.zones;return b?b.checkState(Ca.f,a):Eg},Eg={active:!0,isWhitelisted:function(){return!0}};var Hg=vb,Ig=[],Jg=!1,Kg=function(a){return z["dataLayer"].push(a)},Lg=function(a){var b=!1;return function(){!b&&S(a)&&w(Uf(a));b=!0}},Ug=function(){for(var a=!1;!Jg&&0<Ig.length;){Jg=!0;delete tg.eventModel;var b=Ig.shift();if(S(b))try{b.call(vg)}catch(La){}else if($a(b))a:{var c=b;if(ib(c[0])){for(var d=c[0].split("."),e=d.pop(),f=c.slice(1),g=tg,h=0;h<d.length;h++){if(void 0===g[d[h]])break a;g=g[d[h]]}try{g[e].apply(g,f)}catch(La){}}}else{var k=b;if(k&&("[object Arguments]"==Object.prototype.toString.call(k)||
Object.prototype.hasOwnProperty.call(k,"callee"))){a:{var l=b;if(l.length&&ib(l[0])){var m=rg[l[0]];if(m){b=m(l);break a}}b=void 0}if(!b){Jg=!1;continue}}var n=void 0,p=void 0,t=b,r=t._clear;for(p in t)t.hasOwnProperty(p)&&"_clear"!==p&&(r&&wg(p,void 0),wg(p,t[p]));var v=!1,y=t.event;if(y){t.hasOwnProperty("gtm.uniqueEventId")||(t["gtm.uniqueEventId"]=Wf(),wg("gtm.uniqueEventId",t["gtm.uniqueEventId"]));n=t["gtm.uniqueEventId"];wa=y;var H=Fg(n);if(H.active){var G=Lg(t.eventCallback),D=t.eventTimeout;
D&&z.setTimeout(G,Number(D));v=Hg(n,y,H.isWhitelisted,G,t.eventReporter)}}Kb||(Kb=t["gtm.start"])&&Cg();var K,C=t,E=n,A=y,B=tg;wa=null;a=v||a}Jg=!1}return!a},Vg=function(){var a=Ug();try{var b=z["dataLayer"].hide;if(b&&void 0!==b[Ca.f]&&b.end){b[Ca.f]=!1;var c=!0,d;for(d in b)if(b.hasOwnProperty(d)&&!0===b[d]){c=!1;break}c&&(b.end(),b.end=null)}}catch(e){}return a},Wg=function(){var a=Ta("dataLayer",[]),b=Ta("google_tag_manager",{});b=b["dataLayer"]=b["dataLayer"]||{};sb.push(function(){b.gtmDom||(b.gtmDom=!0,a.push({event:"gtm.dom"}))});ng.push(function(){b.gtmLoad||
(b.gtmLoad=!0,a.push({event:"gtm.load"}))});var c=a.push;a.push=function(){var b=[].slice.call(arguments,0);c.apply(a,b);for(Ig.push.apply(Ig,b);300<this.length;)this.shift();return Ug()};Ig.push.apply(Ig,a.slice(0));w(Vg)};var Xg,Yg,Zg;
var ya=function(a,b){var c={"gtm.element":a,"gtm.elementClasses":a.className,"gtm.elementId":a["for"]||ta(a,"id")||"","gtm.elementTarget":a.formTarget||a.target||""};if(b&&ah)if("LINK_CLICK"==b)c["gtm.elementUrl"]=a.href;else if("FORM_SUBMIT"==b){var d=a.action;d&&d.tagName&&(d=a.cloneNode(!1).action);c["gtm.elementUrl"]=d}c.hasOwnProperty("gtm.elementUrl")||(c["gtm.elementUrl"]=(a.attributes&&a.attributes.formaction?a.formAction:"")||a.action||a.href||a.src||a.code||a.codebase||"");return c},ph=
function(a){lb.hasOwnProperty("autoEventsSettings")||(lb.autoEventsSettings={});var b=lb.autoEventsSettings;b.hasOwnProperty(a)||(b[a]={});return b[a]},qh=function(a,b,c){ph(a)[b]=c},fb=function(a,b,c,d){var e=ph(a),f=Ia(e,b,d);e[b]=c(f)},W=function(a,b,c){var d=ph(a);return Ia(d,b,c)},rh=function(){};var sh=/(^|\.)doubleclick\.net$/i,th=/^(www\.)?google(\.com?)?(\.[a-z]{2})?$/,Aa=function(a,b,c){for(var d=String(b||P.cookie).split(";"),e=[],f=0;f<d.length;f++){var g=d[f].split("="),h=va(g[0]);if(h&&h==a){var k=va(g.slice(1).join("="));k&&!1!==c&&(k=decodeURIComponent(k));e.push(k)}}return e},vh=function(a,b,c,d,e,f){f&&(b=encodeURIComponent(b));var g=a+"="+b+"; ";c&&(g+="path="+c+"; ");e&&(g+="expires="+e.toGMTString()+"; ");var h;h="auto"==d?uh():[d||"none"];for(var k=0;k<h.length;k++){var l=
g,m=h[k],n=c;if(sh.test(z.location.hostname)||"/"==n&&th.test(m))break;"none"!=h[k]&&(l+="domain="+h[k]+";");var p=P.cookie;P.cookie=l;if(p!=P.cookie||0<=Nf(Aa(a),b))return!0}return!1},wh=function(a){if("none"==a)return 0;0==a.indexOf(".")&&(a=a.substr(1));return a.split(".").length},xh=function(a){var b=a;b?(1<b.length&&b.lastIndexOf("/")==b.length-1&&(b=b.substr(0,b.length-1)),0!=b.indexOf("/")&&(b="/"+b),a=b):a="/";return"/"==a?1:a.split("/").length},uh=function(){var a=V(z.location,"host",!0).split(".");
if(4==a.length&&/^[0-9]*$/.exec(a[3]))return["none"];for(var b=[],c=a.length-2;0<=c;c--)b.push(a.slice(c).join("."));b.push("none");return b};var ea=function(a){var b=P;return yh?b.querySelectorAll(a):null},zh=!1;if(P.querySelectorAll)try{var Ah=P.querySelectorAll(":root");Ah&&1==Ah.length&&Ah[0]==P.documentElement&&(zh=!0)}catch(a){}var yh=zh;var Bh=function(a){for(var b=[],c=P.cookie.split(";"),d=new RegExp("^\\s*"+a+"=\\s*(.*?)\\s*$"),e=0;e<c.length;e++){var f=c[e].match(d);f&&b.push(f[1])}var g=[];if(!b||0==b.length)return g;for(var h=0;h<b.length;h++){var k=b[h].split(".");3==k.length&&"GCL"==k[0]&&k[1]&&g.push(k[2])}return g};var Ch=/^\w+$/,Dh=/^[\w-]+$/,Eh=/^\d+\.fls\.doubleclick\.net$/;function Fh(a){return a&&"string"==typeof a&&a.match(Ch)?a:"_gcl"}function Gh(a){if(a){if("string"==typeof a){var b=Fh(a);return{na:b,ka:b}}if(a&&"object"==typeof a)return{na:Fh(a.dc),ka:Fh(a.aw)}}return{na:"_gcl",ka:"_gcl"}}function Hh(a){var b=U(z.location.href),c=V(b,"host",!1);if(c&&c.match(Eh)){var d=V(b,"path").split(a+"=");if(1<d.length)return d[1].split(";")[0].split("?")[0]}}
function Ih(a){return a.filter(function(a){return Dh.test(a)})}var Kh=function(a){var b=Hh("gclaw");if(b)return b.split(".");var c=Gh(a);if("_gcl"==c.ka){var d=Jh();if(d&&(null==d.L||"aw.ds"==d.L))return[d.qa]}return Ih(Bh(c.ka+"_aw"))},Lh=function(a){var b=Hh("gcldc");if(b)return b.split(".");var c=Gh(a);if("_gcl"==c.na){var d=Jh();if(d&&("ds"==d.L||"aw.ds"==d.L))return[d.qa]}return Ih(Bh(c.na+"_dc"))};
function Jh(){var a=U(z.location.href),b=V(a,"query",!1,void 0,"gclid"),c=V(a,"query",!1,void 0,"gclsrc");if(!b||!c){var d=V(a,"fragment");b=b||qg(d,"gclid");c=c||qg(d,"gclsrc")}return void 0!==b&&b.match(Dh)?{qa:b,L:c}:null}
var Xa=function(a,b,c){var d=Gh(a);c=c||"auto";b=b||"/";var e=Jh();if(null!==e){var f=(new Date).getTime(),g=new Date(f+7776E6),h=["GCL",Math.round(f/1E3),e.qa].join(".");e.L&&"aw.ds"!=e.L||vh(d.ka+"_aw",h,b,c,g,!0);"aw.ds"!=e.L&&"ds"!=e.L||vh(d.na+"_dc",h,b,c,g,!0)}},Mh=function(){var a=Hh("gac");if(a)return decodeURIComponent(a);for(var b=[],c=P.cookie.split(";"),d=/^\s*_gac_(UA-\d+-\d+)=\s*(.+?)\s*$/,e=0;e<c.length;e++){var f=c[e].match(d);f&&b.push({zb:f[1],value:f[2]})}var g={};if(b&&b.length)for(var h=
0;h<b.length;h++){var k=b[h].value.split(".");"1"==k[0]&&3==k.length&&k[1]&&(g[b[h].zb]||(g[b[h].zb]=[]),g[b[h].zb].push({timestamp:k[1],qa:k[2]}))}var l=[],m;for(m in g)if(g.hasOwnProperty(m)){for(var n=[],p=g[m],t=0;t<p.length;t++)n.push(p[t].qa);n=Ih(n);n.length&&l.push(m+":"+n.join(","))}return l.join(";")};var Nh;a:{Nh="G"}var Oh={"":"n",UA:"u",AW:"a",DC:"d",GTM:Nh},sa=function(a){var b=Ca.f.split("-"),c=b[0].toUpperCase();return(Oh[c]||"i")+"1c"+(a&&"GTM"===c?b[1]:"")};var Sh={},Th,Uh;
var ci=function(){};var ki="www.googletagmanager.com/gtm.js";
var li=ki,ab=function(a,b,c,d){pa(a,b,c,d)},ba=function(a,b,c){u(a,b,c)},cb={},Oa=function(a,b,c){var d=cb[a];if(void 0===d){var e=function(a,b){return function(){a.status=b;for(var c=2==b?a.vb:a.bb,d=0;d<c.length;d++)z.setTimeout(c[d],0)}};d={status:1,vb:[],bb:[],bc:void 0};d.rd=u(a,e(d,2),e(d,3));cb[a]=d}0===d.status&&(d.bc(),d.status=2);2===d.status?b&&b():3===d.status?c&&c():1===d.status&&(b&&d.vb.push(b),c&&d.bb.push(c))},mi=function(a,b){cb[a]={status:0,vb:[],bb:[],bc:b,rd:null}},ca=function(){return z.location.href},
bb=function(a){return V(U(a),"fragment")},T=function(a,b){return Z(a,b||2)},ma=function(a,b,c){b&&(a.eventCallback=b,c&&(a.eventTimeout=c));return Kg(a)},aa=function(a,b){z[a]=b},q=function(a,b,c){var d=z;b&&(void 0===d[a]||c&&!d[a])&&(d[a]=b);return d[a]},db=function(a,b,c){return hg(a,b,c)},x=function(a,b,c,d){var e=!d&&"http:"==z.location.protocol;e&&(e=2!==kb());return(e?b:a)+c},ia=function(a){var b=0;
return b},Bb=function(a){},ja=function(a){var b=!1;return b},eb=function(a,b){return Of(a,b)},za=function(a){qh(a,"init",!0)};
var Db=void 0,Ra=function(a){if(!Db){var b=function(){var a=P.body;if(a)if(q("MutationObserver"))(new MutationObserver(function(){for(var a=0;a<Db.length;a++)w(Db[a])})).observe(a,{childList:!0,subtree:!0});else{var b=!1;ab(a,"DOMNodeInserted",function(){b||(b=!0,w(function(){b=!1;for(var a=0;a<Db.length;a++)w(Db[a])}))})}};Db=[];P.body?b():w(b)}Db.push(a)},kb=function(){var a=li;a=a.toLowerCase();for(var b="https://"+a,c="http://"+a,d=1,e=P.getElementsByTagName("script"),f=0;f<e.length&&100>f;f++){var g=
e[f].src;if(g){g=g.toLowerCase();if(Zf(g,c))return 3;1===d&&Zf(g,b)&&(d=2)}}return d};var ni=new RegExp(/^(.*\.)?(google|youtube|blogger|withgoogle)(\.com?)?(\.[a-z]{2})?\.?$/),oi={customPixels:["nonGooglePixels"],html:["customScripts","customPixels","nonGooglePixels","nonGoogleScripts","nonGoogleIframes"],customScripts:["html","customPixels","nonGooglePixels","nonGoogleScripts","nonGoogleIframes"],nonGooglePixels:[],nonGoogleScripts:["nonGooglePixels"],nonGoogleIframes:["nonGooglePixels"]},pi={customPixels:["customScripts","html"],html:["customScripts"],customScripts:["html"],nonGooglePixels:["customPixels",
"customScripts","html","nonGoogleScripts","nonGoogleIframes"],nonGoogleScripts:["customScripts","html"],nonGoogleIframes:["customScripts","html","nonGoogleScripts"]},qi=function(a,b){for(var c=[],d=0;d<a.length;d++)c.push(a[d]),c.push.apply(c,b[a[d]]||[]);return c},Ng=function(a){var b=Z("gtm.whitelist");
var c=b&&qi(Pf(b),oi),d=Z("gtm.blacklist")||Z("tagTypeBlacklist")||[];ni.test(z.location&&z.location.hostname)&&(d=Pf(d),d.push("nonGooglePixels","nonGoogleScripts"));var e=d&&qi(Pf(d),pi),f={};return function(g){var h=g&&g[Ya];if(!h)return!0;if(void 0!==f[h.a])return f[h.a];var k=a(h.a);if(b){var l;if(l=k)a:{if(0>Nf(c,h.a))if(h.b&&0<h.b.length)for(var m=0;m<h.b.length;m++){if(0>
Nf(c,h.b[m])){l=!1;break a}}else{l=!1;break a}l=!0}k=l}var n=!1;if(d){var p;if(!(p=0<=Nf(e,h.a)))a:{for(var t=h.b||[],r=new Qf,v=0;v<e.length;v++)r.set(e[v],!0);for(v=0;v<t.length;v++)if(r.get(t[v])){p=!0;break a}p=!1}n=p}return f[h.a]=!k||n}};var _eu=function(a){var b=String(Z("gtm.elementUrl")||a[Xc]||""),c=U(b);return b};_eu.a="eu";_eu.b=["google"];var _e=function(){return wa};_e.a="e";_e.b=["google"];var vi=function(a,b){this.h=a;this.s=b};vi.prototype.toString=function(){var a=""+this.h;1<this.s&&(a=a+"-"+this.s);return a};var wi=function(a,b){this.ub=a;this.Ka=b};wi.prototype.toString=function(){return""+this.Ka+"."+this.ub};var zi=function(a,b){var c=new xi(null,a,b);yi(c);return c},xi=function(a,b,c){this.Ob=Math.floor(L().getTime()/864E5);this.Ia=b||"auto";this.ta=c||"/";var d=wh(this.Ia),e=xh(this.ta);this.N=a||new vi(d,e);this.m=[];this.I=new Qf},Bi=function(a,b,c){b&&(""==c.ub?Ai(a,b):(a.I.contains(b)||a.m.push(b),a.I.set(b,c)))},Ci=function(a,b){for(var c=0;c<b.length;c++)Bi(a,b[c][0],b[c][1])},Ai=function(a,b){var c=Nf(a.m,b);0<=c&&a.m.splice(c,1);a.I.set(b,void 0)},Di=function(a){for(var b=[],c=0;c<a.m.length;c++){var d=
a.m[c];b.push([d,a.I.get(d)])}return b},Ei=function(a){for(var b=0,c=0;c<a.m.length;c++)b=Math.max(b,a.I.get(a.m[c]).Ka);return 864E5*b};xi.prototype.toString=function(){if(0==this.m.length)return"";for(var a=[],b=0;b<this.m.length;b++){var c=this.m[b];a.push(""+c+"."+this.I.get(c).toString())}return"GAX1."+this.N.toString()+"."+a.join("!")};
var Fi=function(a,b){for(var c=new Date,d=xh(a.ta),e=[],f=0;f<a.m.length;f++){var g=a.m[f];a.I.get(g).Ka<a.Ob&&e.push(g)}for(f=0;f<e.length;f++)Ai(a,e[f]);if(a.m.length>(b||10))return!1;c.setTime(Ei(a));if("auto"!=a.Ia)return vh("_gaexp",a.toString(),a.ta,a.Ia,c);for(var h=uh(),k=0;k<h.length;k++)if("none"!=h[k]&&(a.N=new vi(wh(h[k]),d),vh("_gaexp",a.toString(),a.ta,h[k],c)))return!0;return!1},yi=function(a){for(var b=a.N.h,c=a.N.s,d=Aa("_gaexp"),e=[],f=0;f<d.length;f++){var g=Gi(a,d[f]);g&&e.push(g)}$f(e,
function(a,d){var e=a.N,f=d.N;return e.h==f.h&&e.s==f.s?!1:e.h==b&&e.s==c?!0:f.h==b&&f.s==c?!1:e.h==b?f.h!=b||e.s<f.s:f.h==b?!1:e.s==c?f.h!=b&&(f.s!=c||e.h<f.h):f.s==c?!1:e.h<f.h||e.h==f.h&&e.s<f.s});a.N=0<e.length?e[0].N:new vi(b,c);for(f=e.length-1;0<=f;f--)Ci(a,Di(e[f]))},Gi=function(a,b){var c=b.match(/GAX1\.([^.]+).(.*)/);if(c){var d;a:{var e=(c[1]||"").split("-");if(!(0==e.length||2<e.length)){var f=va(e[0]);if(0!=f.length){var g=2==e.length?va(e[1]):"1";if(Mf(f)&&Mf(g)){d=new vi(X(f),X(g));
break a}}}d=void 0}if(d){for(var h=new xi(d,a.Ia,a.ta),k=(c[2]||"").split("!"),l=0;l<k.length;l++){var m=k[l].split(".");if(3==m.length){if(!Mf(m[1]))return;Bi(h,m[0],new wi(m[2],X(m[1])))}}return h}}};var _f=function(a){var b=String(Z("gtm.referrer")||P.referrer);if(!b)return b;var c=U(b);return b};_f.a="f";_f.b=["google"];var Ki=function(a){var b=z.location,c;(c=a[Mc]?a[Mc]:Z("gtm.url"))&&(b=U(String(c)));var d=b.href,e=d.indexOf("#"),f=0>e?d:d.substr(0,e);a[xc]&&(f=V(b,a[xc],a[Re],a[Wc],a[Ee]));return f},_u=Ki;_u.a="u";_u.b=["google"];var _eq=function(a){return String(a[Zb])==String(a[$b])};_eq.a="eq";_eq.b=["google"];var gb=new String("undefined"),tb=function(a){this.resolve=function(b){for(var c=[],d=0;d<a.length;d++)c.push(a[d]===gb?b:a[d]);return c.join("")}};tb.prototype.toString=function(){return this.resolve("undefined")};tb.prototype.valueOf=tb.prototype.toString;var Ui={},ub=function(a,b){var c=Wf();Ui[c]=[a,b];return c},Vi=function(a){var b=a?0:1;return function(a){var c=Ui[a];if(c&&S(c[b]))c[b]();Ui[a]=void 0}};var Wi=String.prototype.trim?function(a){return a.trim()}:function(a){return/^[\s\xa0]*([\s\S]*?)[\s\xa0]*$/.exec(a)[1]},Xi=function(a,b){return a<b?-1:a>b?1:0};var Yi;a:{var Zi=Fb.navigator;if(Zi){var $i=Zi.userAgent;if($i){Yi=$i;break a}}Yi=""};var aj=function(a){aj[" "](a);return a};aj[" "]=function(){};var cj=function(a,b){var c=bj;return Object.prototype.hasOwnProperty.call(c,a)?c[a]:c[a]=b(a)};var dj=-1!=Yi.indexOf("Opera"),ej=-1!=Yi.indexOf("Trident")||-1!=Yi.indexOf("MSIE"),fj=-1!=Yi.indexOf("Edge"),gj=-1!=Yi.indexOf("Gecko")&&!(-1!=Yi.toLowerCase().indexOf("webkit")&&-1==Yi.indexOf("Edge"))&&!(-1!=Yi.indexOf("Trident")||-1!=Yi.indexOf("MSIE"))&&-1==Yi.indexOf("Edge"),hj=-1!=Yi.toLowerCase().indexOf("webkit")&&-1==Yi.indexOf("Edge"),ij;
a:{var jj="",kj=function(){var a=Yi;if(gj)return/rv:([^\);]+)(\)|;)/.exec(a);if(fj)return/Edge\/([\d\.]+)/.exec(a);if(ej)return/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/.exec(a);if(hj)return/WebKit\/(\S+)/.exec(a);if(dj)return/(?:Version)[ \/]?(\S+)/.exec(a)}();kj&&(jj=kj?kj[1]:"");if(ej){var lj,mj=Fb.document;lj=mj?mj.documentMode:void 0;if(null!=lj&&lj>parseFloat(jj)){ij=String(lj);break a}}ij=jj}
var nj=ij,bj={},oj=function(a){return cj(a,function(){for(var b=0,c=Wi(String(nj)).split("."),d=Wi(String(a)).split("."),e=Math.max(c.length,d.length),f=0;0==b&&f<e;f++){var g=c[f]||"",h=d[f]||"";do{var k=/(\d*)(\D*)(.*)/.exec(g)||["","","",""],l=/(\d*)(\D*)(.*)/.exec(h)||["","","",""];if(0==k[0].length&&0==l[0].length)break;b=Xi(0==k[1].length?0:parseInt(k[1],10),0==l[1].length?0:parseInt(l[1],10))||Xi(0==k[2].length,0==l[2].length)||Xi(k[2],l[2]);g=k[3];h=l[3]}while(0==b)}return 0<=b})};var xb=function(a,b){var c="";ej&&!pj(a)&&(c='<script>document.domain="'+document.domain+'";\x3c/script>'+c);var d="<!DOCTYPE html><html><head><script>var inDapIF=true;\x3c/script>"+c+"</head><body>"+b+"</body></html>";if(qj)a.srcdoc=d;else if(rj){var e=a.contentWindow;if(e){var f=e.document;f.open("text/html","replace");f.write(d);f.close()}}else sj(a,d)},qj=hj&&"srcdoc"in document.createElement("IFRAME"),rj=gj||hj||ej&&oj(11)||fj,sj=function(a,b){ej&&oj(7)&&!oj(10)&&6>tj()&&uj(b)&&(b=vj(b));var c=
function(){var c=a.contentWindow;c&&(c.goog_content=b,c.location.replace("javascript:window.goog_content"))};ej&&!pj(a)?wj(a,c):c()},tj=function(){var a=navigator.userAgent.match(/Trident\/([0-9]+.[0-9]+)/);return a?parseFloat(a[1]):0},pj=function(a){try{var b;var c=a.contentWindow;try{var d;if(d=!!c&&null!=c.location.href)b:{try{aj(c.foo);d=!0;break b}catch(e){}d=!1}b=d}catch(e){b=!1}return b}catch(e){return!1}},xj=0,wj=function(a,b){var c="goog_rendering_callback"+xj++;Fb[c]=b;a.src="javascript:'<script>(function() {document.domain = \""+
document.domain+'";var continuation = window.parent.'+c+";window.parent."+c+" = null;continuation();})()\x3c/script>'"},uj=function(a){for(var b=0;b<a.length;++b)if(127<a.charCodeAt(b))return!0;return!1},vj=function(a){for(var b=unescape(encodeURIComponent(a)),c=Math.floor(b.length/2),d=[],e=0;e<c;++e)d[e]=String.fromCharCode(256*b.charCodeAt(2*e+1)+b.charCodeAt(2*e));1==b.length%2&&(d[c]=b.charAt(b.length-1));return d.join("")};/*
 Copyright (c) 2014 Derek Brans, MIT license https://github.com/krux/postscribe/blob/master/LICENSE. Portions derived from simplehtmlparser, which is licensed under the Apache License, Version 2.0 */

var Nj=function(a,b,c,d,e){var f=a+"{"+(b+": "+c+(d?" !important":""))+"}";e&&(f=e+"{"+f+"}");var g=document;if(g.createStyleSheet){var h=Kj(g),k=h.rules.length;h.insertRule(f,k);return function(){h.deleteRule?h.deleteRule(k):h.removeRule(k);h.insertRule("x {}",k)}}var l=Lj(f,g);Mj(l,g);var m=l.parentNode;return function(){m.removeChild(l)}},Oj=null,Kj=function(a){if(Oj)return Oj;for(var b=a.styleSheets.length-1;0<=b;b--){var c=a.styleSheets[b],d=c.ownerNode;if(d&&d.parentNode&&"HEAD"==d.parentNode.tagName)return Oj=
c}0==a.styleSheets.length&&a.createStyleSheet();return Oj=a.styleSheets[0]},Lj=function(a,b){var c=(b||document).createElement("style");void 0!==c.cssText?c.cssText=a:c.innerHTML=a;return c},Mj=function(a,b){var c=b||document,d=c.getElementsByTagName("head")[0];d||(d=c.createElement("head"),c.body.parentNode.insertBefore(d,c.body));d.appendChild(a)};var Vj={},Wj=void 0,Xj=function(a){var b=Vj[a];b||(b={id:a,w:[],pa:0,Ab:null,ib:void 0,pb:!1},Vj[a]=b);Wj=b},Zj=function(a,b,c,d){var e=Wj;if(!yh||!e)return!1;var f={id:e.id+":"+e.w.length,tc:b,ea:[],oc:c,O:a,Wa:0,Sa:d||null,Nb:0,oa:!1};e.w.push(f);null===a?(f.oa=!0,b(null)):Yj(e);return!0},ak=function(a){var b=Nj(a,"visibility","hidden",!0);return function(){S(b)&&b.apply();b=null}},bk=function(a,b,c,d){var e=b;if(!rb){var f=ak(a.F);sb.push(f);e=function(a,c){var d=b(a,c);f();return d}}return Zj(a,
e,c,d)},Yj=function(a){if(!a.pb){for(var b=a.pa;b<a.w.length;b++){var c=a.w[b],d=b==a.pa;if(!c.oa&&!ck(d,c))break;c.oa&&d&&a.pa++}a.w.length>a.pa?(a.Ab||(a.Ab=z.setTimeout(function(){a.Ab=null;Yj(a)},80)),rb||a.ib||(a.ib=function(){w(function(){Yj(a)})},pa(P,"DOMContentLoaded",a.ib))):dk(a)}},dk=function(a){for(var b=0;b<a.w.length;b++){var c=a.w[b];if(c.O)for(var d=ea(c.O.F)||[],e=0;e<d.length;e++){var f=d[e];f.gtmProgressiveApplied&&f.gtmProgressiveApplied[c.id]||(ek(f,c.id),c.ea.push(gk(f,c.id)))}}},
ck=function(a,b){var c=[];if(b.O){var d=hk(b.O,b.id),e=null;b.Sa&&(e=hk(b.Sa,b.id+"-t"));for(var f=0;f<d.length;f++){var g=d[f],h;if(null!=e&&(h=e.length>f?e[f]:null,!h&&!rb&&(null===b.Sa.v||b.Nb+c.length<b.Sa.v)))break;c.push({element:g,ud:h})}}if(!rb&&b.oc&&(!a||null==b.O.v||b.O.v!=b.Wa+c.length))return!1;for(var k=0;k<c.length;k++){var l=c[k].element,m=c[k].ud,n;b.Wa++;ek(l,b.id);m&&(b.Nb++,n=b.id+"-t",ek(m,n));var p=b.tc(l,m);S(p)&&b.ea.push(p);b.ea.push(gk(l,b.id));m&&n&&b.ea.push(gk(m,n))}if(b.O.v&&
b.O.v==b.Wa||rb)b.oa=!0;return!0},ek=function(a,b){a.gtmProgressiveApplied||(a.gtmProgressiveApplied={});a.gtmProgressiveApplied[b]=!0},gk=function(a,b){return function(){a.gtmProgressiveApplied&&delete a.gtmProgressiveApplied[b]}},hk=function(a,b){for(var c=ea(a.F)||[],d=[],e=0;e<c.length;e++){var f=c[e];if(!f.gtmProgressiveApplied||!f.gtmProgressiveApplied[b]){if(a.M&&!ik(f))break;d.push(f)}}return d},ik=function(a){if(rb)return!0;for(;a;){if(a.nextSibling)return!0;a=a.parentNode}return!1};var Ek=function(a){if(!a)return!1;if(a[Yb]&&$a(a[$b])){for(var b=a[$b],c=0;c<b.length;c++)if(a[$b]=b[c],Rf(a))return!0;return!1}return Rf(a)};var $k=29,al=[],bl=[],Og=[],cl=new Qf,dl=[],el=[],mh=[],nh=[],fl=function(){this.U=[]};fl.prototype.set=function(a,b){this.U.push([a,b]);return this};fl.prototype.resolve=function(a,b){for(var c={},d=0;d<this.U.length;d++){var e=Rg(this.U[d][0],a,b),f=Rg(this.U[d][1],a,b);c[e]=f}return c};var gl=function(a){this.index=a};gl.prototype.resolve=function(a,b){var c=Og[this.index];if(c&&!b(c)){var d=c[Za];if(a){if(a.get(d))return;a.set(d,!0)}c=Rg(c,a,b);a&&a.set(d,!1);return Rf(c)}};
var _M=function(a){return new gl(a)},hl=function(a){this.resolve=function(b,c){for(var d=[],e=!1,f=0;f<a.length;f++){var g=Rg(al[a[f]],b,c);g===gb&&(e=!0);d.push(g)}return e?new tb(d):d.join("")}},_T=function(a){return new hl(arguments)},il=function(a){function b(b){for(var c=1;c<a.length;c++)if(a[c]==b)return!0;return!1}this.resolve=
function(c,d){var e=Rg(a[0],c,d);if(a[0]instanceof gl&&b(8)&&b(16)){if(e===gb)return e;var f=Ga();cl.set(f,e);return'google_tag_manager["'+Ca.f+"\"].macro('"+f+"')"}e=String(e);for(var g=1;g<a.length;g++)e=Fk[a[g]](e);return e}},_E=function(a,b){return new il(arguments)},jl=function(a,b){this.D=a;this.xa=b},_R=function(a,b){return new jl(a,b)};
var Rg=function(a,b,c){var d=a;if(a instanceof gl||a instanceof fl||a instanceof hl||a instanceof il)return a.resolve(b,c);if(!(a instanceof jl))if($a(a)){d=[];for(var e=0;e<a.length;e++)d[e]=Rg(a[e],b,c)}else if(a&&"object"==typeof a){d={};for(var f in a)a.hasOwnProperty(f)&&(d[f]=Rg(a[f],b,c))}return d},ml=function(){for(var a=[_eq,_e,'_event',_M(0),'gtm.js','1840408_2147479553',_ua,true,'UA-72303300-1',false,'\x26tid',{10:8},1,'UA-63770508-7',{10:13},2,_u,'Page URL','Page Hostname','host','Page Path','path',_f,'Referrer','Event'],b=[],c=0;c<a.length;c++)b[c]=
ll(c,a);return b},ll=function(a,b){var c=b[a],d=c;if(c instanceof gl||c instanceof il||c instanceof hl||c instanceof jl)d=c;else if($a(c)){d=[];for(var e=0;e<c.length;e++)d[e]=ll(c[e],b)}else if("object"==typeof c){d=new fl;for(var f in c)c.hasOwnProperty(f)&&d.set(b[f],ll(c[f],b))}return d},ol=function(a,b){for(var c=b?b.split(","):[],d=0;d<c.length;d++){var e=c[d]=c[d].split(":");0==a&&(e[1]=
al[e[1]]);if(1==a){var f=nl(e[0]);e=c[d]={};for(var g=0;g<f.length;g++){var h=bl[f[g]];e[h[0]]=h[1]}}if(2==a)for(g=0;4>g;g++)e[g]=nl(e[g]);3==a&&(c[d]=al[e[0]]);if(4==a)for(g=0;2>g;g++)if(e[g]){e[g]=e[g].split(".");for(var k=0;k<e[g].length;k++)e[g][k]=al[e[g][k]]}else e[g]=[];5==a&&(c[d]=e[0])}return c},nl=function(a){var b=[];if(!a)return b;for(var c=0,d=0;d<a.length&&c<$k;c+=6,d++){var e=a&&a.charCodeAt(d)||65;if(65!=e){var f;f=65<e&&90>=e?e-65:97<=e&&122>=e?e-97+26:95==e?63:48<=e?e-48+52:62;1&
f&&b.push(c);2&f&&b.push(c+1);4&f&&b.push(c+2);8&f&&b.push(c+3);16&f&&b.push(c+4);32&f&&b.push(c+5)}}return b},pl=function(a,b,c){a.push.apply(a,ol(b,c))};var ql;
var Qg=function(a,b){if(null===a||void 0===a)return a;if(b.propertyRenamingRequired){var c={},d;for(d in a)if(a.hasOwnProperty(d)){var e=tl[d];e&&0==e.indexOf("vtp_")&&(c[e]=a[d])}c.__metadata=b;return c}return a},wl=function(a){},xl=function(a,b){},Tg=function(a){};var yl,zl;var Kl=function(a){return function(){}},Ll=function(a){return function(){}};var Ml=function(a){var b=this;this.i=a;this.la=this.fc=!1;this.Ra=[];this.La=[];this.C=function(){b.la||Vf(b.Ra);Yf(b,1);if(Nb[a])for(var c=0;c<Nb[a].length;c++)Nb[a].shift().C()};this.B=function(){b.la||Vf(b.La);Yf(b,2);if(Nb[a])for(var c=0;c<Nb[a].length;c++)Nb[a].shift().B()};this.H=vb},Nl=function(a,b){a.Ra.push(b)},Ol=function(a,b){a.La.push(b)},Pl=function(a){this.P=[];this.wb=[];this.Qb={};this.Wb=[];this.ba=0;this.tb={};this.yb={};this.xb={};this.event=a};Pl.prototype.addListener=function(a){this.Wb.push(a)};
var Ql=function(a){0<a.ba||Vf(a.Wb)},Rl=function(a,b,c,d,e,f){if(!c.la){a.P[b]=c;void 0==d&&(d=[]);void 0==e&&(e=[]);void 0==f&&(f=[]);d=$a(d)?d.slice():["or",d];e=$a(e)?e.slice():[e];f=$a(f)?f.slice():[f];a.Qb[b]=d;a.tb[b]=0<e.length;a.yb[b]=0<f.length;a.ba++;var g=function(){0<a.ba&&!a.tb[b]&&!a.yb[b]&&a.ba--;Ql(a)};Nl(c,g);Ol(c,g)}},Wl=function(a){for(var b=[],c={},d=0;d<a.P.length;c={W:c.W},d++)if(c.W=a.P[d],c.W){var e=a.Qb[d],f=a.tb[d],g=a.yb[d];if(0!=e.length||f||g){if(0<e.length)for(var h=
Sl(e,c.W.H),k=0;k<e.length;k++)e[k]instanceof jl&&e[k].D!=d&&Tl(a,e[k].D,h);(f||g)&&Ul(a,d,function(a){return function(){0<a.W.G.ba&&a.W.G.ba--;Ql(a.W.G)}}(c))}else b.push(d)}for(d=0;d<b.length;d++)a.P[b[d]].H();for(d=0;d<a.wb.length;d++){var l=a.wb[d];Vl(l);0<l.length&&l[0].H()}},Tl=function(a,b,c){a.P[b]&&(Nl(a.P[b],function(){c(b,!0)}),Ol(a.P[b],function(){c(b,!1)}))},Sl=function(a,b){var c=vb,d=!1;return function(e,f){var g;a:{for(var h=0;h<a.length;h++)if(a[h]instanceof jl&&a[h].D===e||a[h]===
e){g=h;break a}g=-1}d||0>g||("or"==a[0]?f?(d=!0,b()):(a.splice(g,1),1==a.length&&(d=!0,c())):f?(a.splice(g,1),1==a.length&&(d=!0,b())):(d=!0,c()))}},Ul=function(a,b,c){var d=[],e=!1,f=function(b){var c,g,h=el[b];if(a.event.g(h)){}else g=Xl(h,b,a.event.g,a);if(c=g){var k=Yl(b,!0);0<k.length&&f(k[0].D);d.push(c);var l=Yl(b,!1);0<l.length&&
f(l[0].D)}else e=!0};f(b);if(!e){for(var g=0;g<d.length;g++){var h=d[g],k=Yl(h.i,!0);if(0<k.length){var l=d[g-1],m=Zl(h);Nl(l,m);0==k[0].xa?Ol(l,m):Ol(l,c)}var n=Yl(h.i,!1);0<n.length&&(m=Zl(d[g+1]),Nl(h,m),0==n[0].xa?Ol(h,m):Ol(h,c))}Nl(d[d.length-1],c);Ol(d[d.length-1],c);a.wb.push(d)}},Yl=function(a,b){var c=b?Oe:ef,d=el[a],e=void 0===d[c]?[]:d[c];return $a(e)?e:[e]},Zl=function(a){return function(){a.H()}},Vl=function(a){for(var b=[],c=0;c<a.length;c++){var d=a[c],e=d.i,f=Mb[e],g=f.firingOption;
if(0!=g&&(1==g&&void 0!==d.G.xb[e]||2==g&&void 0!==f.state)&&(b.push(d),2==f.state&&c!=a.length-1)){var h=Yl(a[c+1].i,!0);if(0<h.length&&1==h[0].xa)for(++c;c<a.length;c++)b.push(a[c])}}var k=$l(b),l;for(l in k)if(k.hasOwnProperty(l)){for(var m=void 0,n=void 0,p=k[l],t=p[0],r=p[p.length-1],v,y=0;y<a.length;y++){var H=a[y];!m&&H.i==t&&0<y&&(m=a[y-1]);H.i==r&&y<a.length-1&&(n=a[y+1]);if(-1<Nf(p,H.i))if(v=a.splice(y,1)[0],H.i==r)break;else y--}if(v){var G=Number(l),D=m,K=n;if(D){var C=D.Ra[0],E=D.La[0],
A=D;A.Ra=[];A.La=[];Nl(D,C);Ol(D,E)}if(D&&K){var B=Zl(K);Nl(D,B);var I=Yl(D.i,!1);0<I.length&&I[0].D!=G&&0==I[0].xa&&Ol(D,B);var J=Yl(K.i,!0);0<J.length&&J[0].D!=G&&0==J[0].xa&&Ol(D,B)}}}},$l=function(a){for(var b={},c=0;c<a.length;c++){var d=a[c],e=[],f=function(a){var b=Yl(a,!0);0<b.length&&f(b[0].D);e.push(a);var c=Yl(a,!1);0<c.length&&f(c[0].D)};f(d.i);b[d.i]=e}am(a,b);return b},am=function(a,b){for(var c=0;c<a.length;c++){var d=a[c].i,e;for(e in b)if(b.hasOwnProperty(e)&&e!=d&&-1<Nf(b[e],d)){delete b[d];
break}}};var bm=function(a,b,c){return function(){a[Ad]=b.C;a[Bd]=b.B;var d=b.i,e=b.G&&b.G.xb[d],f=Mb[d]&&Mb[d].state,g=e?void 0!==e:b.fc||b.la,h=Mb[d]&&Mb[d].firingOption,k=h&&2==h,l=h&&1==h;if(!g&&void 0===f||!g&&!k||!k&&!l){Yf(b,0);var m=b.G?b.G.event:void 0,n=a;n=Rg(n,new Qf,c);a=n;if(m){}Rf(a,b.C,b.B)}else k&&0==f||l&&0==e?Nb[d].push(b):k&&1==f||l&&1==e?b.C():b.B()}},Xl=function(a,b,c,d){function e(a){return a.i===b}var f=function(){var a=d&&d.P;return a&&Of(a,e)}()||new Ml(b);f.G=d;Nl(f,Kl(a));Ol(f,Ll(a));f.H=bm(a,f,c);return f};
var fm=!1,_ua=function(a,b,c){function d(a){var b=[].slice.call(arguments,0);b[0]=n+b[0];z[l()].apply(window,b)}function e(b,c){void 0!==a[c]&&d("set",b,a[c])}function f(a,b){return void 0===b?b:a(b)}function g(a,b){if(b)for(var c in b)b.hasOwnProperty(c)&&d("set",a+c,b[c])}function h(){var b=function(a,b,c){if(!Ha(b))return!1;for(var e=Ia(Object(b),c,[]),f=0;e&&f<e.length;f++)d(a,e[f]);return!!e&&0<e.length},c;a[ed]?c=Z("ecommerce"):
a[dd]&&(c=a[dd].ecommerce);if(!Ha(c))return;c=Object(c);var e=Ia(a[wd],"currencyCode",c.currencyCode);void 0!==e&&d("set","&cu",e);b("ec:addImpression",c,"impressions");if(b("ec:addPromo",c[c.promoClick?"promoClick":"promoView"],"promotions")&&c.promoClick){d("ec:setAction","promo_click",c.promoClick.actionField);return}for(var f="detail checkout checkout_option click add remove purchase refund".split(" "),g=0;g<f.length;g++){var h=c[f[g]];if(h){b("ec:addProduct",h,"products");d("ec:setAction",f[g],
h.actionField);break}}}function k(a,b,c){var d=0;if(void 0!==a)for(var e in a)if(a.hasOwnProperty(e)&&(c&&r[e]||!c&&void 0===r[e])){var f=v[e]?Ja(a[e]):a[e];"anonymizeIp"!=e||f||(f=void 0);b[e]=f;d++}return d}Ta("GoogleAnalyticsObject",a[ee]||"ga");var l=function(){return z.GoogleAnalyticsObject},m=Ta(l(),function(){var a=z[l()];a.q=a.q||[];a.q.push(arguments)});m.l=Number(L());var n="",p="";"string"!=typeof a[sf]?(p=Ga(),n=p+"."):""!==
a[sf]&&(p=a[sf],n=p+".");var t=!1;
var y={name:p};m("create",a[Pb],y);d("set","&gtm",sa(!0));var G;a[Ud]&&d("require","linkid","linkid.js");d("set","hitCallback",function(){if(S(a[Cd]))a[Cd]();else{var c=a[wd],d=c&&c.hitCallback;S(d)&&d()}b()});if(a[of]){}else if(a[pf]){}else if(a[rf]){}else if(a[qf]){}else if(a[Vc]){}else if(a[Tc]){}else if(a[nf]){}else{a[ld]&&(d("require","ec","ec.js"),h());if(a[cd]&&!a[nd]){var J="_dc_gtm_"+String(a[Pb]).replace(/[^A-Za-z0-9-]/g,"");d("require","displayfeatures",void 0,{cookieName:J})}G?d("send","pageview",G):d("send","pageview");}if(!fm){var O=a[Rc]?"u/analytics_debug.js":"analytics.js";a[Kd]&&!a[Rc]&&(O="internal/"+O);fm=
!0;u(ka("https:","http:","//www.google-analytics.com/"+O,t),function(){z[l()].loaded||c()},c)}};_ua.a="ua";_ua.b=["google"];var im=function(){var a=[];return function(b,c){if(void 0===a[b]){var d=dl[b]&&Rg(dl[b],new Qf,c),e=d;d&&(e=Ek(d));a[b]=[e,d]}return a[b]}},jm=function(a,b){for(var c=b[0],d=0;d<c.length;d++)if(!a.aa(c[d],a.g)[0])return!1;var e=b[2];for(d=0;d<e.length;d++)if(a.aa(e[d],a.g)[0])return!1;return!0},km=!1;
Hg=function(a,b,c,d,e){switch(b){case "gtm.js":if(km)return!1;km=!0;break;case "gtm.sync":if(Z("gtm.snippet")!=Jb)return!1}for(var f={id:a,name:b,Fa:d||vb,ja:nl(),Pa:nl(),aa:im(),g:Ng(c)},g=[],h=0;h<mh.length;h++)if(jm(f,mh[h])){g[h]=!0;for(var k=f,l=mh[h],m=l[1],n=0;n<m.length;n++)k.ja[m[n]]=!0;var p=l[3];for(n=0;n<p.length;n++)k.Pa[p[n]]=!0}else g[h]=!1;var R=[];for(var M=0;M<$k;M++)if(f.ja[M]&&!f.Pa[M])if(f.g(el[M])){}else{R[M]=
el[M];}f.ua=R;for(var oa=new Pl(f),fa=0;fa<$k;fa++)if(f.ja[fa]&&!f.Pa[fa])if(f.g(el[fa])){}else{var La=f.ua[fa],fk=Xl(La,fa,f.g,oa);Rl(oa,fa,fk,La[Yc],La[Oe],La[ef]);if(La[Ob])break}oa.addListener(f.Fa);Wl(oa);Ql(oa);e&&S(e)&&e({passingRules:g,resolvedTags:f.ua});
if("gtm.js"==b||"gtm.sync"==b)a:{}for(var jg in f.ua)if(f.ua.hasOwnProperty(jg)){var kg=f.ua[jg];if(void 0==kg[Za]||!Zf(kg[Za],"_implicit"))return!0}return!1};var mm=function(){};var nm={};var sm=function(){};var lm={macro:function(a){if(cl.contains(a))return cl.get(a)}};lm.dataLayer=vg;lm.onHtmlSuccess=Vi(!0);lm.onHtmlFailure=Vi(!1);lm.callback=function(a){Va.hasOwnProperty(a)&&S(Va[a])&&Va[a]();delete Va[a]};
lm.Bc=function(){var a=z.google_tag_manager;a||(a=z.google_tag_manager={});lb=a;if(a[Ca.f]){var b=lb.zones;b&&b.registerNatural(Ca.f)}else{a[Ca.f]=lm;ci();rh();al.push.apply(al,ml());pl(bl,0,"10:0,10:1,11:2,2:3,3:4,10:6,13:7,0:8,9:9,8:9,15:9,5:9,6:9,1:11,12:9,7:9,14:12,0:13,1:14,14:15,10:16,11:17,11:18,4:19,11:20,4:21,10:22,11:23,11:24");pl(Og,1,"G,AAAM,AAA0,AAAED,AAAAM,CAAAQ");pl(dl,1,"Z");pl(el,1,"g_f,g9tD");pl(mh,2,"B:D::");pl(nh,4,"5.5:");for(var c=0;c<el.length;c++){var d=el[c],e=1;d[le]?e=2:
d[xf]&&(e=0);Mb[c]={firingOption:e,state:void 0};Nb[c]=[]}Dg();Wg();var n=z;if("interactive"==P.readyState&&!P.createEventObject||"complete"==P.readyState)dg();else{pa(P,"DOMContentLoaded",dg);pa(P,"readystatechange",dg);if(P.createEventObject&&P.documentElement.doScroll){var p=!0;try{p=!n.frameElement}catch(H){}p&&fg()}pa(n,"load",dg)}"complete"===P.readyState?og():pa(z,"load",og);sm();mm();a:{}}};
lm.Bc();var _vs="res_ts:1452549497950000,srv_cl:181779496,ds:live,cv:2";
})()
